### ISSUE TITLE
Load local content

### ISSUE THREAD

**Issue by ghost** [OmniVirt/OmniVirt-iOS-SDK#1]
Hi,

I would like to know if there is any way to store local video and load to the player ?

Second question, could you tell me in which files I have to add this code 

```java
FullscreenVRPlayer.launch(MainActivity.this,
                          CONTENT_ID, // Replace with your Content ID
                          true,       // Autoplay
                          false       // Run in Cardboard mode
                          );
```

Thanks for your help

**Comment by baddth** [comment]
@Zirconiumirish, unfortunately our player don't support local playback. All video need to be uploaded into OmniVirt.com, by doing this, our backend will make sure your videos are playable cross-platform and can simplify integration into a single code line above.

From the code that you mentioned, you'll need to replace the CONTENT_ID into your video ID after uploaded on OmniVirt.

Please let us know if you have any questions!

Thanks,
Brad
