### ISSUE TITLE
Probleme Swift 3.1 / Swift 4.0

### ISSUE THREAD

**Issue by ghost** [OmniVirt/OmniVirt-iOS-SDK#2]
Hi I have this problem when i'm trying to import the VRPlayer 

Module compiled with Swift 3.1 cannot be imported in Swift 4.0:Pods/OmniVirtSDK/VRKit.framework/Modules/VRKit.swiftmodule/arm64.swiftmodule

Any help for this ?

Thanks

**Comment by baddth** [comment]
Apology for the issue. From my understanding, I first thought this is already supported. But will double check with the team to see what could be the issue.

**Comment by baddth** [comment]
Hi @Zirconiumirish ,

Just did the full test and found that the latest version of OmvirtSDK works well with both Swift 3 and Swift 4.0. If you still have an issue, could you please describe more about the problem you are facing, like, the part of code that you are currently using.

Part of the problem could be that you may need to a pod update then clean build to fix the error. 
https://stackoverflow.com/questions/44399109/xcode-9-module-compiled-with-swift-3-1-cannot-be-imported-in-swift-4-0/46218030#46218030

Please let us know if you have any questions.

Thanks,
Brad
