### ISSUE TITLE
Update OmnivirtSDK Module compiled with Swift 3.2

### ISSUE THREAD

**Issue by keshwans** [OmniVirt/OmniVirt-iOS-SDK#3]
I have upgraded XCode to 9.0 to build the app for iOS 11 and getting this compile error:
Module compiled with Swift 3.1 cannot be imported in Swift 3.2: ./Pods/OmniVirtSDK/OmniVirtSDK.framework/Modules/OmniVirtSDK.swiftmodule/arm.swiftmodule

**Comment by michaelpurnell** [comment]
+1

**Comment by baddth** [comment]
Apology for the issue. From my understanding, I first thought this is already supported in our CocoaPod. But will double check with the team to see what could be the issue.

**Comment by nuuneoi** [comment]
Hi all,

Just did the full test and found that the latest version of OmvirtSDK works well with both Swift 3.2 and Swift 4.0. If you still have an issue, could you please describe more about the problem you are facing, like, the part of code that you are currently using.

Thanks !

**Comment by michaelpurnell** [comment]
Just had to do a pod update then clean build to get rid of the error. It works now. 

https://stackoverflow.com/questions/44399109/xcode-9-module-compiled-with-swift-3-1-cannot-be-imported-in-swift-4-0/46218030#46218030

**Comment by baddth** [comment]
Sounds great! Thanks for update. And glad to hear that the issue has been resolved for you.
